### ISSUE TITLE
C23 0402 10uF 25V...在哪里可以买到呢.jpg

### ISSUE THREAD

**Issue by oldgerman** [peng-zhihui/Ctrl-FOC-Lite#4]
这个开发板Vin MAX是24V，ME3116手册说Cin（R23）取值为2.2~10uF
0402目前见到10uF，最高耐压是16V，这种肯定不能用
0402目前见到25V ，最高容值是4.7uF，村田的GRM155R61E475ME15D，应该可以
请问各位实际使用的是啥型号？（0402电容中的战斗机😅）

**Comment by Coder-Chouchou** [comment]
0402耐压50V的我在淘宝慕芯旗舰店买的，实际焊接的时候看起来有点感觉像0603的hhhh，能焊，没问题。
