### ISSUE TITLE
请问这个设计是几层的PCB板子？

### ISSUE THREAD

**Issue by franva** [peng-zhihui/Ctrl-FOC-Lite#8]
你好雉辉君和大家,

硬件小白 两个问题。
一是 请问这个板子的设计是几层的。 问这个的原因是我家附近有可以做两层的PCB板子的设备。如果是两层 我就在家旁边做了。不然就要到中国做了。

二是，如何自己就能看出设计中的PCB是几层的？
这样下次就不用再问了。

多谢

**Comment by peng-zhihui** [comment]
4层的，可以在Altium的stack manager里面看

**Comment by franva** [comment]
多谢~!
