### ISSUE TITLE
请问大家都用什么软件打开志辉君的Altium PCB项目?

### ISSUE THREAD

**Issue by franva** [peng-zhihui/Ctrl-FOC-Lite#9]
我去查看了一下 Altium 的价格,本来想着如果不贵 就买了吧.

结果一看,  一个月 $380澳元/月................ (https://www.altium.com/altium-designer)

这.....这还怎么学下去..... 作为一个被志辉君精彩的视频吸引到入迷的 刚开始的小白, 这简直是当头一棒.

请问大家都怎么解决的啊?

**Comment by stig3** [comment]
国内都是盗版的，不商用不会被追责
或者可以用立创EDA打开，前提是AD文件是ASCII格式的

**Comment by franva** [comment]
@stig3  多谢， 我也找到啦 ^^ 

顺便问一下 PCB板子打好以后， 上面要焊接上去的这些小硬件(比如说那个小屏幕， 还有那些我叫不上名字的东西） 都在哪里买啊？ 志辉君 好像没有给出名字或者链接。
硬件小白也想搞一个， 但是不知道从哪里弄那些板子上焊接的小硬件。

能解释一下吗？
谢谢

**Comment by stig3** [comment]
如果你连常规的元器件都不认识的话，可能稚晖君的项目对你来说难度有点大。。
国内有个立创硬件开源平台 https://oshwhub.com/
里面的硬件开源项目都有BOM，也可也商城一键下单元器件，建议先从简易的项目练练手，可以去看一下
另外，嵌入式的项目，数电/模电/单片机不说要精通，至少要了解一下，不然还是很难的。

**Comment by franva** [comment]
@stig3 多谢大佬指点。
对，我的确是电子，硬件方面几乎什么都不懂，是小白。但是看到雉辉君的项目 特别感兴趣。我自己也需要做这些东西用在自己的项目上。

大佬能推荐一些很棒的具体的帮新手上道的课程吗？
再次感谢
